# Generated by Django 4.1.7 on 2023-04-05 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppColegio', '0002_entregable_estudiante_profesor'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregable',
            name='estudiante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppColegio.estudiante'),
        ),
    ]
