# Generated by Django 4.1.7 on 2023-04-05 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppColegio', '0003_entregable_estudiante'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='estudiante',
            field=models.ForeignKey(null='Desconocido', on_delete=django.db.models.deletion.CASCADE, to='AppColegio.estudiante'),
            preserve_default='Desconocido',
        ),
        migrations.AlterField(
            model_name='entregable',
            name='estudiante',
            field=models.ForeignKey(null='Desconocido', on_delete=django.db.models.deletion.CASCADE, to='AppColegio.estudiante'),
        ),
    ]
